version: '2'
services:
  opa:
    image: openpolicyagent/opa:0.36.0
    ports:
      - 8181:8181
    # WARNING: OPA is NOT running with an authorization policy configured. This
    # means that clients can read and write policies in OPA. If you are
    # deploying OPA in an insecure environment, be sure to configure
    # authentication and authorization on the daemon. See the Security page for
    # details: https://www.openpolicyagent.org/docs/security.html.
    command:
      - "run"
      - "--server"
      - "/policies/rego/envoy.rego"
      - "--log-level=error"
    #  - "--log-format=json-pretty"
    #  - "--set=decision_logs.console=true"
    volumes:
      - ${PWD}:/policies/rego
